const data = {
  code: 0,
  data: [
    {
      id: '1',
      menuName: '系统管理',
      menuCode: '',
      parentId: '',
      type: 'DIR',
      icon: 'T',
      orderNum: '1',
      component: '',
      router: '',
      state: 'active',
      createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      children: [
        {
          id: '10',
          menuName: '用户管理',
          menuCode: 'system:user:list',
          parentId: '1',
          type: 'MENU',
          icon: 'T',
          orderNum: '1',
          component: 'system/user/index',
          router: 'user',
          state: 'active',
          createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          children: [
            {
              id: '100',
              menuName: '用户查询',
              menuCode: 'system:user:query',
              parentId: '10',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '101',
              menuName: '用户创建',
              menuCode: 'system:user:create',
              parentId: '10',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '102',
              menuName: '用户更新',
              menuCode: 'system:user:update',
              parentId: '10',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '103',
              menuName: '用户删除',
              menuCode: 'system:user:delete',
              parentId: '10',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
          ],
        },
        {
          id: '11',
          menuName: '角色管理',
          menuCode: 'system:role:list',
          parentId: '1',
          type: 'MENU',
          icon: 'T',
          orderNum: '1',
          component: 'system/role/index',
          router: 'role',
          state: 'active',
          createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          children: [
            {
              id: '110',
              menuName: '角色查询',
              menuCode: 'system:role:query',
              parentId: '11',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '111',
              menuName: '角色创建',
              menuCode: 'system:role:create',
              parentId: '11',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '112',
              menuName: '角色更新',
              menuCode: 'system:role:update',
              parentId: '11',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '113',
              menuName: '角色删除',
              menuCode: 'system:role:delete',
              parentId: '11',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
          ],
        },
      ],
    },
    {
      id: '2',
      menuName: '系统监控',
      menuCode: '',
      parentId: '',
      type: 'DIR',
      icon: 'T',
      orderNum: '1',
      component: '',
      router: '',
      state: 'active',
      createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
      children: [
        {
          id: '20',
          menuName: '在线用户',
          menuCode: 'monitor:online:list',
          parentId: '2',
          type: 'MENU',
          icon: 'T',
          orderNum: '1',
          component: 'monitor/online/index',
          router: 'online',
          state: 'active',
          createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          children: [
            {
              id: '200',
              menuName: '在线查询',
              menuCode: 'monitor:online:query',
              parentId: '10',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '201',
              menuName: '用户强退',
              menuCode: 'monitor:online:logout',
              parentId: '20',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
          ],
        },
        {
          id: '21',
          menuName: '定时任务',
          menuCode: 'monitor:job:list',
          parentId: '2',
          type: 'MENU',
          icon: 'T',
          orderNum: '1',
          component: 'monitor/job/index',
          router: 'job',
          state: 'active',
          createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
          children: [
            {
              id: '210',
              menuName: '任务查询',
              menuCode: 'monitor:job:query',
              parentId: '21',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '211',
              menuName: '任务创建',
              menuCode: 'monitor:job:create',
              parentId: '21',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '212',
              menuName: '任务更新',
              menuCode: 'monitor:job:update',
              parentId: '21',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
            {
              id: '213',
              menuName: '任务删除',
              menuCode: 'monitor:job:delete',
              parentId: '21',
              type: 'BUTTON',
              icon: 'T',
              orderNum: '1',
              component: '',
              router: '',
              state: 'active',
              createdAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              updatedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
              deletedAt: '@datetime("yyyy-MM-dd HH:mm:ss")',
            },
          ],
        },
      ],
    },
  ],
  message: 'success',
};
